### ISSUE TITLE
import.sql for postgres

### ISSUE THREAD

**Issue by Eitol** [szerhusenBC/jwt-spring-security-demo#1]
This is my import,sqk for running the project using postgres

CREATE TABLE usuario
(
  id integer NOT NULL,
  username character varying(50) NOT NULL,
  password character varying(100) NOT NULL,
  firstname character varying(50) NOT NULL,
  lastname character varying(50) NOT NULL,
  enabled boolean,
  lastpasswordresetdate timestamp without time zone NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE authority
(
  id integer NOT NULL,
  name character varying(50) NOT NULL,
  CONSTRAINT authority_pkey PRIMARY KEY (id)
);

CREATE TABLE user_authority
(
  user_id integer NOT NULL,
  authority_id integer NOT NULL,
  CONSTRAINT fk_authority_id_user_authority FOREIGN KEY (authority_id)
      REFERENCES authority (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_usuario_user_authority FOREIGN KEY (user_id)
      REFERENCES usuario (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

INSERT INTO usuario (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, LASTPASSWORDRESETDATE)
             VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', TRUE, to_date('01-06-2016','dd-MMM-yyyy'));
INSERT INTO usuario (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, LASTPASSWORDRESETDATE)
             VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', TRUE, to_date('01-06-2016','dd-MMM-yyyy'));
INSERT INTO usuario (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, LASTPASSWORDRESETDATE)
             VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', FALSE, to_date('01-06-2016','dd-MMM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);

**Comment by szerhusenBC** [comment]
Thanks for providing your import SQL! I have to see, how I can integrate that into to project.

**Comment by szerhusenBC** [comment]
I didn't find a proper way to integrate this into the source code and I think it isn't necessary for the goal of the project. But I will mention your script in the readme section.
