### ISSUE TITLE
Unable to access API via curl

### ISSUE THREAD

**Issue by alinmateut** [szerhusenBC/jwt-spring-security-demo#101]
Whenever I try to run in my terminal 
`curl localhost:8080/auth --data "username=admin&password=admin"`
it gives me an 401 Unauthorized status. How can I fix this?

**Comment by cbvictorio** [comment]
On your curl command, are you specifying the method request flag, i think it is "-X POST"

**Comment by ccennis** [comment]
i am also having this issue and i am doing it both with postman and passing it with "-X POST" --  no matter what it returns 401 Unauthorized.

**Comment by szerhusenBC** [comment]
Closed, because I published a complete new version.

**Comment by szerhusenBC** [comment]
Closed, because I published a complete new version.
