### ISSUE TITLE
Share DB schema 

### ISSUE THREAD

**Issue by sathiyaraj-tag** [szerhusenBC/jwt-spring-security-demo#104]
Hi,  I'm trying to connect my sql database with your code. Can you share your db schema

**Comment by guantianmin** [comment]
发件人：sathiyaraj_tag <notifications@github.com>
发送日期：2019-07-23 00:21:54
收件人：szerhusenBC/jwt-spring-security-demo <jwt-spring-security-demo@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[szerhusenBC/jwt-spring-security-demo] Share DB schema (#104)
Hi, I'm trying to connect my sql database with your code. Can you share your db schema

**Comment by szerhusenBC** [comment]
Just start the demo and you can see the schema in the H2-Console under _/h2-console_
