### ISSUE TITLE
String cannot be resolved to a type

### ISSUE THREAD

**Issue by linchen2chris** [szerhusenBC/jwt-spring-security-demo#107]
I am java fresher, I just clone and run mvn spring-boot:run, and got error
"String cannot be resolved to a type"

I am using open-jdk 11

**Comment by szerhusenBC** [comment]
@linchen2chris Hi, I can't reproduce this. When I start the project via Maven with OpenJDK 11.0.2 I have no problems. I downloaded the JDK from http://jdk.java.net/archive/

When you execute the command "java --version" in your console what does it say?

**Comment by szerhusenBC** [comment]
Closed this one due to inactivity.
