### ISSUE TITLE
where does BCryptPasswordEncoder be used?

### ISSUE THREAD

**Issue by joeyUOFA** [szerhusenBC/jwt-spring-security-demo#108]
Hi,

I saw PasswordEncoder is defined, but it is not been used in any where. How do you verify the password when use logs in?

Thanks

**Comment by maxwellt** [comment]
It is registered as a bean in the [WebSecurityConfig](https://github.com/szerhusenBC/jwt-spring-security-demo/blob/56f5fb0a94a0d9afa40a3966836baf4f23a13af3/src/main/java/org/zerhusen/config/WebSecurityConfig.java).

**Comment by szerhusenBC** [comment]
@joeyUOFA : Like @maxwellt already mentioned it, it's configured as a @Bean and Spring is using it automatically as password decoder.
