### ISSUE TITLE
org.hibernate.dialect.MySQL5Dialect does not support sequences

### ISSUE THREAD

**Issue by yepesluis** [szerhusenBC/jwt-spring-security-demo#11]
Hi and thanks for the code. This is not an issue, it is more a doubt. You suggested that it could be possible to add a MySQL database. However, it doest not support sequences. So, what could it be done in order to not get problems with the algorithm but change the GenerationType.SEQUENCE in the class Authority:
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "authority_seq")

error:  javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory: org.hibernate.dialect.MySQL5Dialect does not support sequences

Thanks again.

**Comment by Neuw84** [comment]
With @GeneratedValue(strategy=GenerationType.IDENTITY) it should work

**Comment by szerhusenBC** [comment]
Yeah, you're right. I will mention this in the documentation.

**Comment by yepesluis** [comment]
Yes thank you.  I used GenerationType.AUTO, it worked!
