### ISSUE TITLE
Authentication process.

### ISSUE THREAD

**Issue by vanrin** [szerhusenBC/jwt-spring-security-demo#13]
Can anyone explain me how the password comparison work in this project?

**Comment by krasowskiM** [comment]
There is no "password comparison" as the passwords aren't stored in the dbs as a strings. What they stored as are hashes, and you can see in the security configuration there is PasswordEncoder instance invoked - BCryptPasswordEncoder. And on registration process it should hash the password and store the hash in db or some other repository and when user wants to log in, it matches the password input with the stored hash.  See https://docs.spring.io/spring-security/site/docs/4.0.1.RELEASE/apidocs/org/springframework/security/crypto/password/PasswordEncoder.html and its implementations. I'm not sure if it works explicitly like that in this project, but I've mainly met this approach.

**Comment by szerhusenBC** [comment]
Thanks to @krasowskiM, this is a good explanation about what Spring Security does here.

@vanrin I didn't change the password comparison mechanics from Spring Security. So if you want to know in depth how it works, please consult the Spring docs, guides etc. In addition you could take a look into their source code are ask in their forums. I hope this answers satisfy you enough, so I close this ticket now.
