### ISSUE TITLE
Getting authentication errors with new pages

### ISSUE THREAD

**Issue by psotos** [szerhusenBC/jwt-spring-security-demo#14]
Hi Stephan! 

I'm probably doing something wrong but I had no way to contact you other than creating an issue because I couldn't find your email address. You may contact me at psotos at epicproportionstour dot com. I see you are also in the music business which is super cool! 

In any case, I have created a new RestController and mirrored the code from the MethodProtectedRestController, and my new Restful endpoint gets a 401 status whether i am logged in or not. Here is the new code:

```
package com.eptent.repository;

import com.eptent.model.Campaign;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.security.access.prepost.PreAuthorize;


/**
 * @author psotos
 *
 */
@RepositoryRestResource(collectionResourceRel = "campaign", path = "campaign")
@PreAuthorize("hasRole('GM')")
public interface CampaignRepository extends MongoRepository<Campaign, String> {
	Campaign findById(String id);
	Campaign findByName(String name);
	

}
```

I also tried this and get the same problem:
```
package com.eptent.routes;


import java.util.concurrent.atomic.AtomicLong;

import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;



@RestController
public class HelloTestController {
	


	    private static final String template = "Hello, %s!";
	    private final AtomicLong counter = new AtomicLong();

	    @RequestMapping(value="hellotest", method=RequestMethod.GET)
	    @PreAuthorize("hasRole('ADMIN')")
	    public ResponseEntity<?> hellotest(@RequestParam(value="name", defaultValue="World") String name) {
	    	
	        
	        return ResponseEntity.ok(new HelloTest(counter.incrementAndGet(),
	                            String.format(template, name)).getContent());
	    }
	}

```
Any help is greatly appreciated!

**Comment by Epsuchti** [comment]
I'm in the similar Problem. 

I think in your case it is because of the Wrong Call of "/hellotest".

Did you try to open the "hellotest" in the Browser?

Or did you changed the function "adminServiceBtn" to call your Function?

If you tryed to open it in the Browser you are on the same Problem as i am. 

I don't know how to submit the JWT in the Request Header if the user types a different URL to the Browser. :-)

Would be greate if sb can help.

**Comment by krasowskiM** [comment]
@psotos 
It may not be the issue, but how does your authorities interpretation work? I had a similar problem when I wanted to get rid of the "ROLE_" part of authority string and Spring Security works only with this kind of strings as authorities - in your case "hasRole(ROLE_ADMIN/GM)". So what I did to avoid the problem I  stored the roles in the db in the form with "role" part and referred in their interpretation as "USER/ADMIN" when they were received from the db.

**Comment by psotos** [comment]
I figured it out. You simply need to call the auth page with a POST request which has some JSON which passes the username and password. That will then return a valid token.
{
username: admin,
password: admin
}

Now you will be able to make pure restful calls to the other services. We can close this issue.

**Comment by szerhusenBC** [comment]
Hi, thank you both for clearing this question. I'm closing this ticket now.
