### ISSUE TITLE
Always load from DB

### ISSUE THREAD

**Issue by Pyohwan** [szerhusenBC/jwt-spring-security-demo#15]
Hello. I am interested in your project.
You comment "It is not compelling necessary to load the use details from the database." in JwtAuthenticationTokenFilter class.
I look at the JwtUserDetailsServiceImpl class with debug mode. when view web page, always access loadUserByUsername method. So still connect database.

**Comment by szerhusenBC** [comment]
Hi, this comment based on another question: https://github.com/szerhusenBC/jwt-spring-security-demo/issues/10

The comment means, that you mustn't load the user details from the database at that point, but for this demo I'm leaving it as it is. For example you could instead read the user details from the credentials in the token.
