### ISSUE TITLE
Error BadCredentialsException

### ISSUE THREAD

**Issue by Eitol** [szerhusenBC/jwt-spring-security-demo#2]
Hello,
when I try to login from the example page gives me the following error:

**org.springframework.security.authentication.BadCredentialsException .**
![control 2](https://cloud.githubusercontent.com/assets/1043061/14764787/ffc7dfc4-098e-11e6-83d4-0ef91aa1d11e.png)

And I created the database, but not how it can be corrected

regards

**Comment by szerhusenBC** [comment]
Hi, did you get it working?
