### ISSUE TITLE
oauth2 ? :)

### ISSUE THREAD

**Issue by paolog22** [szerhusenBC/jwt-spring-security-demo#21]
thanks man this is so helpful for me..i am waiting for more :) can i folk this ? thanks

**Comment by szerhusenBC** [comment]
You're welcome! 

I think at the moment I don't have enough time for this feature.

Of course you can fork this ;)

**Comment by paolog22** [comment]
i can't login via postman. it says "response body not found"

**Comment by szerhusenBC** [comment]
I thought about this feature and I decided not ti implement this. On the one hand I don't have enough time for that and on the other hand this project should be just a case study for how to implement simple JWT with Spring Boot. So I close this ticket now.

BTW.: There already exists an interesting project for this under https://github.com/pac4j/spring-security-pac4j
