### ISSUE TITLE
User credentials validation

### ISSUE THREAD

**Issue by mupi2015** [szerhusenBC/jwt-spring-security-demo#25]
Thanks for sharing this wonderful project. One thing I don't understand how is it validating the user password(I understand the userName validation part and retrieving user from db using userName)? I have gone through the whole project and even executed the same successfully, If i provide an Incorrect password it is showing BadCredentialsException in UI. would you please explain how is it happening because it is no where written to verify the password.

**Comment by mupi2015** [comment]
by any chance is it getting validated from WebSecurityConfiguration.configureAuthentication and Then authenticationManager.authenticate from the controller?

**Comment by alphabytes** [comment]
@mupi2015  i guess the UsernamePasswordAuthenticationFilter is executed which takes care of authenticating username and password. 

when this authenticationTokenFilterBean is executed it wont find any authToken on the very first request of login... and will skip to the next filter in chain which happens to be UsernamePasswordAuthenticationFilter

find this code below in WebSecurityConfig file.
httpSecurity.addFilterBefore(authenticationTokenFilterBean(), UsernamePasswordAuthenticationFilter.class);

**Comment by mupi2015** [comment]
thanks, @alphabytes, yes it makes sense now. After checking this[documentation ](http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/web/authentication/UsernamePasswordAuthenticationFilter.html) i got a little idea.

**Comment by szerhusenBC** [comment]
Sorry for answering that late! The BadCredentialsException is thrown in _org.springframework.security.authentication.dao.DaoAuthenticationProvider#additionalAuthenticationChecks_.

This method is called in the method _org.zerhusen.security.controller.AuthenticationRestController#createAuthenticationToken_ where i call authenticationManager.authenticate(). I just autowire the AuthenticationManager in the AuthenticationRestController and I get the default implementation from Spring.

So to speak I just use the standard Spring Security authentication.
