### ISSUE TITLE
Use Basic Authentication

### ISSUE THREAD

**Issue by Bash-Ali** [szerhusenBC/jwt-spring-security-demo#29]
Hi Stephan, and thank you for the effort in this project.
How and what do I need to do to use Basic Authentication instead of the raw JSON username and password to request a token? I am unable to find any spring boot project/example that uses both Basic authentication and JWT to maximize security. 
Thank you

**Comment by bfwg** [comment]
Hey, @Bash-Ali 

You can use basic authentication the same way as `formLogin`
Here is a good guide on how to configure it: https://spring.io/guides/gs/securing-web/
I wrote an demo app that use `formLogin` with JWT, the front-end is written in AngularJS.
Angular login post request:
```javascript
    $http({
      url: 'login',
      method: 'POST',
      data: $httpParamSerializerJQLike(self.credentials),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
     })
    .then(function(res) {
      // do something with the response object
    });
```
https://github.com/bfwg/springboot-jwt-starter/blob/master/src/main/resources/static/js/app.js#L70

This is how I configured my `formLogin` in the springboot config file.
```java
        http
             ...
            .formLogin()
                .successHandler(authenticationSuccessHandler)
                .failureHandler(authenticationFailureHandler).and()
             ...
             // logout stuff
```
https://github.com/bfwg/springboot-jwt-starter/blob/master/src/main/java/com/bfwg/config/WebSecurityConfig.java#L68

Full source code can be found in [springboot-jwt-starter](https://github.com/bfwg/springboot-jwt-starter), this project is heavily inspired by [jwt-spring-security-demo](https://github.com/szerhusenBC/jwt-spring-security-demo) and [Cerberus](https://github.com/brahalla/Cerberus).

Let me know if you have more questions. By the way, big thanks to szerhusenBC, I learned a lot from his project.

**Comment by szerhusenBC** [comment]
@bfwg Your're welcome! And thank you for your help!
