### ISSUE TITLE
Logout controller

### ISSUE THREAD

**Issue by cosmonova** [szerhusenBC/jwt-spring-security-demo#3]
Can you provide a method for logout.

**Comment by szerhusenBC** [comment]
Hi, good idea! I will add that.

**Comment by szerhusenBC** [comment]
Hi, I have to revise my answer. There is no need for a logout controller. The server doesn't have any state so there is no information wether a client is logged in or not. Take a look at the logout function in the JS client. You just have to delete the token on the client.
