### ISSUE TITLE
Using MySQL database for user authentication

### ISSUE THREAD

**Issue by snehaananthan** [szerhusenBC/jwt-spring-security-demo#30]
Hi Stephan,

This project is really awesome. I'm learning a lot of Spring security from this. I have one question.

Connecting to MySQL database for user authentication. However, it returns Bad Credentials exception when I try to login. 

In debug mode, I observed that at the time of logging in, it tries to extract username from the JWT token (the authentication request to the login endpoint will never contain a token, as a token will be generated by the server only after a user is authenticated in the login step). 

My question: 
When connecting to MySQL database for user authentication, does the doFilterInternal method in the JwtAuthenticationTokenFilter class need any change? 
If yes, what are they? 
If no, which other files need to be changed?

**Comment by mupi2015** [comment]
This is the answer you are looking for [https://github.com/szerhusenBC/jwt-spring-security-demo#using-another-database](https://github.com/szerhusenBC/jwt-spring-security-demo#using-another-database)
@snehaananthan

**Comment by szerhusenBC** [comment]
@mupi2015 thanks for your help!
