### ISSUE TITLE
How possible you can autowired Spring bean in filter layer? 

### ISSUE THREAD

**Issue by a1ucard** [szerhusenBC/jwt-spring-security-demo#35]
Hi,

I follow your tutorial but my service bean is null in Filter Layer? How can you possible to inject bean into Filter layer ?

**Comment by szerhusenBC** [comment]
Sorry for answering that late! Do you still have that problem or could you solve it? In case that not can you be more precise (do you mean the UserDetailsService is null in the JwtAuthenticationTokenFilter)?

**Comment by szerhusenBC** [comment]
Due to inactivity I'm closing this ticket now.
