### ISSUE TITLE
Can I use Spring web MVC instead of Spring Boot?

### ISSUE THREAD

**Issue by MoAli2016** [szerhusenBC/jwt-spring-security-demo#40]
I am Spring beginner, wanting to learn spring by hand, can I adapt the code to run with spring web mvc instead of Spring Boot?

**Comment by krasowskiM** [comment]
Yeah totally. I've made the project like this. The difference is that you need to run the application on a tomcat that isn't embedded and the configuration cannot be auto.

**Comment by szerhusenBC** [comment]
@krasowskiM Thanks for your answer!

@MoAli2016 Do you need further help? I would close this ticket otherwise.

**Comment by szerhusenBC** [comment]
Closing the ticket now due to inactivity.
