### ISSUE TITLE
How can I refresh after the token time expires?

### ISSUE THREAD

**Issue by silentken** [szerhusenBC/jwt-spring-security-demo#41]
Hi, Thank you for your opensource.
I am practicing with your source. However, it did not refresh after the token time expired.
I hope that the token is refreshed without sign in again. Please let me know what you need to refer to.

**Comment by szerhusenBC** [comment]
Hi! I will implement this in the next time under ticket #20 

There will be an endpoint to refresh your tocken. Please wait for this ticket being implemented.
