### ISSUE TITLE
How to implement a microservices architecture using this aproach without Oauth?

### ISSUE THREAD

**Issue by neonds** [szerhusenBC/jwt-spring-security-demo#42]
I've heard about microservices using oauth2, but for me it's really hard to learn oauth2, I mean, I understood the Oauth2 architecture but in a theorical aproach, in practice it seems to be more dificult. A lot of configuration I think, maybe for huge project. It is enough for me a lot of configuratoin using spring security that I just learn basics before.

Why not configure this project as a common or generic project that you just have to import in your pom or gradle config?

So the developers wont have to care about how to implement JWT, just extend user entity or authority entity, and changes configuration about JWT in file, and provieed a datasource only.

Something like a "spring-boot-starter-jwt"

**Comment by szerhusenBC** [comment]
Hi @neonds!

I had the same idea for a "spring-boot-starter-jwt", but unfortunately I didn't find the time for that yet :/

But please take a look in the readme section for ["Interesting projects"](https://github.com/szerhusenBC/jwt-spring-security-demo#interesting-projects). Perhaps it will help you ...

To be honest when I created this demo I didn't think of big microservice architectures. My intension was more like "_OK, I have **one** REST based Spring Boot app here that I want to use with (maybe) an Angular client and I'd like to have security. How can I achieve that with JWT._"

**Comment by KiranNaikwade** [comment]
Can you please share one example "JWT with micro service architecture" ?
EX :  There will be two servers : Server-A and Server-B
Server-A will generate a token and Server-B will validate the token.

**Comment by szerhusenBC** [comment]
@KiranNaikwade nice idea, but unfortunately I don't have time for that. Maybe anyone else could do that?

**Comment by gdiazs** [comment]
Hi about my original question, but not focus exactly in microservices but maybe for kind tiny projects, I built this.
https://github.com/gdiazs/commons-boot-jwt-security
