### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by chorpitman** [szerhusenBC/jwt-spring-security-demo#48]
Hi, tnx for big work. 
I have a question. When i have to use refresh token?

**Comment by szerhusenBC** [comment]
The token contains a field with the expiration date ("exp" is the key in the claims map). You can use it to verify if a token is expired and isn't valid anymore. In this case you have to refresh your token so that it doesn't expire.

**Comment by chorpitman** [comment]
User gets an access token, stores it in his local storage, the token expires, he knocks on some URL, the filter say that the token expired and returns 401.
UI should check expire day? And if it comes to end ui should send request to refresh token?

**Comment by szerhusenBC** [comment]
That seems to be a bug. The refresh endpoint is secured like a normal endpoint. So a token that is expired will be rejected and you have no chance to refresh it. I will fix that.

**Comment by chorpitman** [comment]
may be better implement one controller which will give refresh and access token. And then use refresh token for get access token.
