### ISSUE TITLE
Problem in MAC

### ISSUE THREAD

**Issue by arellano-gustavo** [szerhusenBC/jwt-spring-security-demo#5]
I have 2 MacBooks Pro retina and your code does not work on them. However, in my Ubuntu SO it works perfect ! What could be the reason?

**Comment by szerhusenBC** [comment]
Hi, I've written this project in UbuntU, but I tested it on my MacBook Pro Retina as well with no problems. Can you describe more precisely what your problem is? Can you post a stack trace. Which version auf Java and Maven do you use?

**Comment by estebangm81** [comment]
This code works fine in my MacBook Pro too.

**Comment by arellano-gustavo** [comment]
I am using Java 1.8
Maven 3.3.3
Mac OS X El Capitan
MacBook Pro Retina 16Gb RAM 512GB HD Core i7
No error messages in the console.

After git clone I did mvn package and then java -jar
jwtdemo-0.0.1-SNAPSHOT.jar

This is the error when I am using admin-admin credentials:
[image: Imágenes integradas 1]

The same procedure works as expected in Ubuntu

Thanks!
Gustavo

2016-05-23 7:56 GMT-05:00 Esteban <notifications@github.com>:

**Comment by szerhusenBC** [comment]
> I am using Java 1.8
> Maven 3.3.3
> Mac OS X El Capitan
> MacBook Pro Retina 16Gb RAM 512GB HD Core i7
> No error messages in the console.

I have exactly the same configuration.

When I do 'mvn clean package' and 'java -jar target/jwtdemo-0.0.1-SNAPSHOT.jar' afterwards the app is running fine. I have no problems using the credentials for admin.

Could you fix the image link? I only see a broken markup.

**Comment by estebangm81** [comment]
> After git clone I did mvn package and then java -jar
> jwtdemo-0.0.1-SNAPSHOT.jar
> 
> This is the error when I am using admin-admin credentials:

That was the error I faced when the SQL to insert the users failed (please, see #4). This was fixed.

**Comment by arellano-gustavo** [comment]
Thanks, Esteban !!!!!!!

That was exactly the problem.

Now it has been fixed.

Cheers,
Gustavo


2016-05-24 9:56 GMT-05:00 Esteban <notifications@github.com>:

**Comment by szerhusenBC** [comment]
@estebangm81: Thanks your help. This issue is closed.
