### ISSUE TITLE
Error when Upgraded to Spring Boot 1.5.6

### ISSUE THREAD

**Issue by hendisantika** [szerhusenBC/jwt-spring-security-demo#53]
Nice share.
But, I got an Error when Upgraded to Spring Boot 1.5.6.

Will you try to latest version of Spring Boot?

Thanks

**Comment by szerhusenBC** [comment]
I will check that.

**Comment by szerhusenBC** [comment]
Hi @hendisantika ,

I just tried the demo with 1.5.6 and got no problems. Did you integrate the demo in you own application? What error do you get?

**Comment by hendisantika** [comment]
Ooo.. It running well now.
I didn't know. 

But, that's OK.

**Comment by szerhusenBC** [comment]
np ;)
