### ISSUE TITLE
customError

### ISSUE THREAD

**Issue by MrFireman** [szerhusenBC/jwt-spring-security-demo#58]
For some reason the normal error handling is not working with this project. 

 I tried to create a new controller which Implements ErrorController, and redirected the /error to my view, but it is keep showing the Whitelabel Error page when for example I try to reach this:
myapp:8000/asd

 Is it because of the Spring Security? Do I have to turn off something to make it work?
 Thank you

**Comment by szerhusenBC** [comment]
Closed, because I published a complete new version.
