### ISSUE TITLE
Token validation on change password and logout

### ISSUE THREAD

**Issue by ntota** [szerhusenBC/jwt-spring-security-demo#67]
First off all I am very thankful for this demo project. It was well explained.
I need below clarifications,
How to handle token validity when user changed his password? invalidate the current token and redirect him to login page, asking him to login with new password ?
 and in case of User logs out?

**Comment by davideas** [comment]
Token is not linked to the password value, it's up to you to generate a new one.

**Comment by szerhusenBC** [comment]
@davideas mentioned it, thx ;)
