### ISSUE TITLE
Extend JwtAuthenticationTokenFilter from GenericFilterBean instead of UsernamePasswordAuthenticationFilter

### ISSUE THREAD

**Issue by szerhusenBC** [szerhusenBC/jwt-spring-security-demo#7]
This enhancement based on the comment https://www.toptal.com/java/rest-security-with-jwt-spring-security-and-java#comment-2797220982.

Actually the JwtAuthenticationTokenFilter extends the UsernamePasswordAuthenticationFilter and the question was why it not extends the simple GenericFilterBean. I checked that and everything seems to work fine. Extending the GenericFilterBean makes the WebSecurityConfig a little bit easier.

**Comment by Gbryson** [comment]
This post was a big help. I was using this example to set up a project using JWT.   I had the JwetAuthenticationTokenFilter setup to extend OncePerRequestFilter.  This worked fine when running locally with HQSLDB and embedded Tomcat.   I have a requirement to deploy in Glassfish.    This solution didn't work, for some reason it looked like the SecurityContext was getting overwritten  or reset somewhere in the security chain.   However, when I switched to the GenericFilterBean, the issue went away.  I don't completely understand why, but I am happy that it works now.
