### ISSUE TITLE
Create tables with MySQL

### ISSUE THREAD

**Issue by pyth0nic** [szerhusenBC/jwt-spring-security-demo#74]
Hello,

Great demonstration and some beautiful code. I'm having a problem autocreating creating tables in mysql like it does with hBase. Any ideas?

Regards
Adrian

**Comment by pyth0nic** [comment]
Ended up using flywaydb https://flywaydb.org/ to get the migrations done.

**Comment by lastlink** [comment]
@pyth0nic could you share your code for using flyawaydb w/ this repository?

**Comment by szerhusenBC** [comment]
@pyth0nic thanks for your help
