### ISSUE TITLE
Move to MongoDB

### ISSUE THREAD

**Issue by psotos** [szerhusenBC/jwt-spring-security-demo#76]
Hi Stephan,

Most of us are using NoSQL these days. I think it would be best to port this demo to MongoDB since you are moving to Spring Boot 2.0 anyway. Also, since moving to Spring boot 2, are you going to make this in a Reactive Style? Let me know if you need help as I am willing to contribute.

**Comment by szerhusenBC** [comment]
Hi Peter,

the scope of this project doesn't lie in a specific kind of database. I assume that people can change the underlying persistence layer themselves. So I won't change it for now.

Furthermore I won't change this project to the reactive style for now. I need the actual approach for myself and a lot people still are using the "old" style. I'm actually focussing on fixing bugs or do some optimizations. But I'm thinking about running this project alongside in the reactive style. If you want, you could help me with that? I didn't use reactive approach so far.

**Comment by psotos** [comment]
Sure I would be happy to help. I've been diving into the reactive style of programming. I have a great handle on it on the front end side with Angular 5 and RXJS, but only beginning at using Spring 5 Reactive and Spring 5 Reactive Security.

**Comment by szerhusenBC** [comment]
Closed, because I published a complete new version.
