### ISSUE TITLE
Why aren't you clearing SecurityContext

### ISSUE THREAD

**Issue by andsamp** [szerhusenBC/jwt-spring-security-demo#78]
The last thing you do in `JwtAuthorizationTokenFilter` is call `chain.doFilter(request, response)`. I'm curious to know why you aren't calling `SecurityContext.clearContext()` or the `context.setAuthentication(null) I`'ve seen in other examples?

Is the `sessionCreationPolicy` effectively taking care of that?

**Comment by pedroviniv** [comment]
I think if the security context is cleared before the authenticated request gets into the controller, the controller wouldn't be able to inject the `Authentication` object which can contain `UserDetails` and `Authority` List in it. (Authentication lives inside the `SpringContext` which lives inside a `ThreadLocal` that can be accessed during the whole thread's life cycle) These data could be read by controller to avoid another call to the database (which is expansive). Spring Security should clear the Security Context automatically before sending the response to the client. If I'm wrong, please, tell me.

**Comment by szerhusenBC** [comment]
Closed, because I published a complete new version.
