### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by 7carlosz** [szerhusenBC/jwt-spring-security-demo#79]
No 'Access-Control-Allow-Origin' header is present on the requested resource

**Comment by kle-pra** [comment]
I don't think CORS request support is implemented, but you can easily add a CORS filter.

**Comment by hamdimefteh** [comment]
I do it and i post it .

**Comment by szerhusenBC** [comment]
@7carlosz does it help you?

**Comment by szerhusenBC** [comment]
Closing this ticket now.
