### ISSUE TITLE
tomcat deployment

### ISSUE THREAD

**Issue by lastlink** [szerhusenBC/jwt-spring-security-demo#82]
Should be able to do a `mvn package` and copy to a tomcat server as a war file. I'm having difficulties setting up the boiler plate.

**Comment by szerhusenBC** [comment]
To be honest I never did this by myself.

It's documented here: https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/htmlsingle/#howto-traditional-deployment

**Comment by lastlink** [comment]
I figured it out, I'm going to do a pull request as this works w/ your current code.

**Comment by hamdimefteh** [comment]
I have solution . I just produce many jar linked with manifestation.mf created by intellij . That work for me !
