### ISSUE TITLE
how to host angular5 app to local IIS folder

### ISSUE THREAD

**Issue by safeenashebi** [szerhusenBC/jwt-spring-security-demo#87]
Have an angular 5 (angular cli) app coded with visual code
backend using webApi in VS 2017.
I am newly with angular coding.How can I publish these two and host to local IIS 
pls any body help

**Comment by lastlink** [comment]
I don't really think that this is related to this project. This is a java spring based api backend. It's not really focused on deployment. If you are using this as your webapi I would not recommend running it on IIS which can run static things like js, html, php, & .net apps. There are ways to make other languages work on them, but would require work on getting them setup. Easiest thing would be to just use a docker tomcat server (which runs/serves java .war files) to get going quickly for trying out deployment of just this service.

**Comment by szerhusenBC** [comment]
@safeenashebi lastlink is right. This isn't related to this project. This project is just about a Java based backend service that is secured with JWT. You should better ask this question at Stackoverflow or similar.

So I'm closing this ticket now.
