### ISSUE TITLE
Use OncePerRequestFilter as base class instead of GenericFilterBean

### ISSUE THREAD

**Issue by pellicceama** [szerhusenBC/jwt-spring-security-demo#9]
Thanks for this great example!

I don't think it's worth opening a pull request over this, but I would recommend anyone using this pattern in production to extend OncePerRequestFilter on the JwtAuthenticationTokenFilter as opposed to GenericFilterBean as it stops the chain from calling the filter multiple times per request, which is critical when doing things asynchronously :-)

`public class JwtAuthenticationTokenFilter extends OncePerRequestFilter {}`

**Comment by reemsky** [comment]
Thanks for the great tip!

**Comment by szerhusenBC** [comment]
Thanks for your hint @pellicceama ! I changed it in the filter

**Comment by jkerak** [comment]
I see this is closed, but looking at the filter example code, does this line need to be there?

`HttpServletRequest httpRequest = (HttpServletRequest) request;`

The request coming in to `doFilterInternal` is already of type `HttpServletRequest`.

**Comment by szerhusenBC** [comment]
You're right, will fix it.

**Comment by szerhusenBC** [comment]
Fixed it!
