### ISSUE TITLE
configuring with postgresql

### ISSUE THREAD

**Issue by vbiginner** [szerhusenBC/jwt-spring-security-demo#90]
Hi Stephan, thanks for the great example.
Instead of using in-memory database I am using postgresql. I have configured it using the properties file as you mentioned in 'Readme'. But its not working. Getting error 
```
Unable to construct current session context [org.springframework.orm.hibernate4.SpringSessionContext]
Caused by: java.lang.ClassNotFoundException: Could not load requested class : org.springframework.orm.hibernate4.SpringSessionContext.  
```
Googled lot about this, not getting the fix. Can you please suggest something..

**Comment by szerhusenBC** [comment]
Hmm. Hard to say. I never used postgresql with Spring. Maybe there is a tutorial on spring.io?

**Comment by vbiginner** [comment]
okay..Thanks for your response.
